CREATE TABLE fact_employee_monthly(
	fact_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_key NUMBER NOT NULL,
	year_number number(4),
	month_number number(2),
	total_reported_hours number(6),
	total_absence_hours number(6),
	medical_leave_days number(3),
	annual_leave_days number(3),
	public_holiday_days number(3),
	exam_leave_hours number(4),
	attendance_days number(3),
	presence_percentage number(5, 2),
	CONSTRAINT fk_monthly_employee FOREIGN KEY (employee_key) REFERENCES dim_employee(employee_key)
);

INSERT INTO fact_employee_monthly(
	employee_key,
	year_number,
	month_number,
	total_reported_hours,
	total_absence_hours,
	medical_leave_days,
	annual_leave_days,
	public_holiday_days,
	exam_leave_hours,
	attendance_days,
	presence_percentage
)
SELECT employee_key, d.year_number, d.month_number, sum(reported_hours), sum(absence_hours),
sum(
	CASE WHEN dat.absence_type = 'Medical Leave' THEN 1 ELSE 0 END
),
sum(
	CASE WHEN dat.absence_type = 'Annual Leave' THEN 1 ELSE 0 END
),
sum(
	CASE WHEN dat.absence_Type = 'Public Holidays' THEN 1 ELSE 0 END
),
sum(
	CASE WHEN dat.absence_type = 'EX' THEN absence_hours ELSE 0 END
),
sum(
	CASE WHEN was_present = 'Y' THEN 1 ELSE 0 END
),
round(
	100 * sum(CASE WHEN was_present='Y' THEN 1 ELSE 0 end) / count(*),
	2
)
FROM fact_employee_daily f
JOIN dim_date d ON d.date_key = f.date_key
LEFT JOIN dim_absence_type dat ON dat.absence_type_key = f.absence_type_key
GROUP BY employee_key, d.year_number, d.month_number;