CREATE TABLE fact_employee_daily(
	fact_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	date_key NUMBER NOT NULL,
	employee_key NUMBER NOT NULL,
	work_type_key NUMBER,
	absence_type_key NUMBER,
	reported_hours number(2),
	absence_hours number(2),
	first_join DATE,
	last_leave DATE,
	total_presence varchar2(64 char),
	was_present char(1),
	was_absent char(1),
	CONSTRAINT fk_daily_date FOREIGN KEY (date_key) REFERENCES dim_date(date_key),
	CONSTRAINT fk_daily_employee FOREIGN KEY (employee_key) REFERENCES dim_employee(employee_key),
	CONSTRAINT fk_daily_work FOREIGN KEY (work_type_key) REFERENCES dim_work_type(work_type_key),
	CONSTRAINT fk_daily_absence FOREIGN KEY (absence_type_key) REFERENCES dim_absence_type(absence_type_key)
);

INSERT INTO fact_employee_daily(
	date_key, employee_key, work_type_key, absence_type_key, reported_hours, absence_hours,
	first_join, last_leave, total_presence, was_present, was_absent
)
SELECT d.date_key, de.employee_key, wt.work_type_key, AT.absence_type_key,
nvl(t.number_of_reported_hours, 0), nvl(eas.absence_hours, 0),
ar.first_join, ar.last_leave,
trunc((ar.last_leave - ar.first_join) * 24) || 'H ' || trunc(MOD((ar.last_leave - ar.first_join) * 24 * 60, 60)) || 'M ' || trunc(MOD((ar.last_leave - ar.first_join) * 24 * 60 * 60, 60)) || 'S',
CASE
	WHEN t.entry_id IS NOT NULL or ar.first_join IS NOT NULL THEN 'Y' ELSE 'N'
END,
CASE
	WHEN a.absence_id IS NOT NULL OR eas.id IS NOT NULL THEN 'Y' ELSE 'N'
END
FROM etl_theory.employee emp
LEFT JOIN etl_theory.timesheet t ON emp.emp_id = t.employee_id
LEFT JOIN etl_theory.attendance_report ar ON lower(emp.email) = lower(ar.email)
LEFT JOIN etl_theory.absences a ON emp.emp_id = a.employee_id AND trunc(a.start_time) = trunc(t.entry_day)
LEFT JOIN etl_theory.exam_absence_schedule eas ON emp.emp_id = eas.employee_id AND trunc(eas.absence_day) = trunc(t.entry_day)
JOIN dim_employee de ON de.employee_id=emp.emp_id AND de.current_flag = 'Y'
JOIN dim_date d ON d.full_date = trunc(t.entry_day)
LEFT JOIN dim_work_type wt ON wt.work_type = t.work_type
LEFT JOIN dim_absence_type AT ON AT.absence_type = coalesce(a.absence_type, eas.absence_type);