CREATE TABLE dim_employee(
	employee_key NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id NUMBER NOT NULL,
	first_name varchar2(64 char),
	last_name varchar2(64 char),
	email varchar2(128 char),
	grade varchar2(64 char),
	department_name varchar2(64 char),
	discipline_name varchar2(64 char),
	location_name varchar2(64 char),
	location_code varchar2(4 char),
	valid_from DATE NOT NULL,
	valid_to DATE NOT NULL,
	current_flag char(1) check(current_flag IN ('Y', 'N'))
);

INSERT INTO dim_employee(
	employee_id,
	first_name,
	last_name,
	email,
	grade,
	department_name,
	discipline_name,
	location_name,
	location_code,
	valid_from,
	valid_to,
	current_flag
)
SELECT e.emp_id, e.first_name, e.last_name, e.email, e.grade, d.name, d.discipline_name,
d.location_name, d.location_code, DATE '2020-01-01', DATE '9999-12-31', 'Y'
FROM etl_theory.employee e
JOIN etl_theory.department d ON e.department_id = d.department_id;