CREATE TABLE dim_work_type(
	work_type_key NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	work_type varchar2(16 char)
);

INSERT INTO dim_work_type (work_type)
SELECT DISTINCT work_type
FROM etl_theory.timesheet
WHERE work_type IS NOT NULL;