CREATE TABLE dim_absence_type(
	absence_type_key NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	absence_type varchar2(32 char)
);

INSERT INTO dim_absence_type(absence_type)
SELECT absence_type
FROM (
	SELECT DISTINCT absence_type
	FROM etl_theory.absences
	UNION
	SELECT DISTINCT absence_type
	FROM etl_theory.exam_absence_schedule
);