CREATE TABLE department(
	department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	department_name varchar2(32 char),
	CONSTRAINT pk_department PRIMARY KEY(department_id)
);

INSERT INTO DEPARTMENT(department_name)
VALUES ('Data and AI');
INSERT INTO DEPARTMENT(department_name)
VALUES ('Development');
INSERT INTO DEPARTMENT(department_name)
VALUES ('Management');
INSERT INTO DEPARTMENT(department_name)
VALUES ('Product Delivery');
INSERT INTO DEPARTMENT(department_name)
VALUES ('HR');
COMMIT;