CREATE TABLE EMPLOYEE(
	person_number number(6) GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar2(64 char),
	last_name varchar2(32 char) NOT NULL,
	hire_date DATE DEFAULT SYSDATE NOT NULL,
	birth_date DATE,
	department_id NUMBER NOT NULL,
	salary number(8, 2) CHECK (salary >= 0),
	manager_id number(6),
	commission_pct number,
	CONSTRAINT pk_employee PRIMARY KEY(person_number),
	CONSTRAINT fk_employee_department FOREIGN KEY(department_id) REFERENCES department(department_id),
	CONSTRAINT fk_employee_manager FOREIGN KEY(manager_id) REFERENCES employee(person_number)
);

DECLARE
	v_emp_count NUMBER := 0;
BEGIN
	SELECT count(*)
	INTO v_emp_count
	FROM employee;
	
	IF v_emp_count = 0 THEN
		FOR i IN 1..2000 LOOP
			INSERT INTO employee(first_name, last_name, birth_date, department_id, salary, manager_id)
			VALUES(
				dbms_random.string('A', 20),
				dbms_random.string('A', 10),
				(SELECT DATE '1980-01-01' + trunc(dbms_random.value(-365, 365))),
				(SELECT department_id FROM department ORDER BY dbms_random.value FETCH FIRST 1 ROW ONLY),
				dbms_random.value(0, 5000),
				(SELECT max(person_number) FROM (SELECT person_number FROM employee ORDER BY dbms_random.value FETCH FIRST 1 ROW ONLY))
			);
		END LOOP;
		COMMIT;
	END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_check_birthdate
BEFORE INSERT OR UPDATE ON employee
FOR EACH ROW
BEGIN
	IF :NEW.birth_date > add_months(:NEW.hire_date, -216) THEN -- 216 = 12 * 18
		RAISE_APPLICATION_ERROR(-20001, 'The employee must be at least 18 years old on the hire date.');
	END IF;
END;
/

INSERT INTO employee(first_name, last_name, birth_date, department_id, salary, manager_id)
VALUES('Alexandru Petrut', 'Ursu', to_date('16-01-2004', 'DD-MM-YYYY'), 1, 1234, 5);
COMMIT;

ALTER TABLE employee
ADD employee_metadata clob CHECK (employee_metadata IS json);

UPDATE EMPLOYEE e
SET employee_metadata = '{
	"phone": "+4077123456",
	"linkedin": "linkedin.com/in/placeholder",
	"languages": ["Romanian", "English"],
	"emergencyContact": {
		"name": "placeholder",
		"phone": "+4077456123"
	}
}'
WHERE e.LAST_NAME = 'Ursu';

UPDATE employee SET commission_pct = dbms_random.value(0, 1);
UPDATE employee SET commission_pct = round(commission_pct, 1);

UPDATE employee
SET commission_pct = NULL
WHERE PERSON_NUMBER IN (
	SELECT PERSON_NUMBER
	FROM (
		SELECT PERSON_NUMBER
		FROM EMPLOYEE
		ORDER BY dbms_random.value
	)
	FETCH FIRST 150 ROWS only
);