CREATE TABLE TIMECARD(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	status varchar2(16 char) CHECK (status IN ('SAVED', 'SUBMITTED', 'APPROVED', 'REJECTED')),
	start_date DATE NOT NULL,
	submission_date DATE,
	employee_id NUMBER(6) NOT NULL,
	CONSTRAINT pk_timecard PRIMARY KEY (id),
	CONSTRAINT fk_timecard_employee FOREIGN KEY(employee_id) REFERENCES employee(person_number)
);

INSERT INTO timecard(status, start_date, submission_date, employee_id)
values('SAVED', to_date('07-05-2026', 'MM-DD-YY'), NULL, 5);
INSERT INTO timecard(status, start_date, submission_date, employee_id)
values('SAVED', to_date('06-29-2026', 'MM-DD-YY'), NULL, 5);
INSERT INTO timecard(status, start_date, submission_date, employee_id)
values('SAVED', to_date('06-22-2026', 'MM-DD-YY'), NULL, 5);
COMMIT;