DECLARE
	TYPE t_table_names IS TABLE OF varchar2(30 char);
	v_table_names t_table_names := t_table_names(
		'WORK_ENTRY',
		'TIMECARD_ENTRY',
		'TIMECARD',
		'PROJECT',
		'EMPLOYEE',
		'DEPARTMENT',
		'TASK'
	);
BEGIN	
	FOR i IN 1..v_table_names.count LOOP
		EXECUTE IMMEDIATE 'DROP TABLE ' || v_table_names(i) || ' CASCADE CONSTRAINTS';
	END LOOP;
	EXCEPTION WHEN OTHERS THEN 
		IF SQLCODE != -942 THEN
			RAISE;
		END IF;
END;
/

--------------------------------------------- DEPARTMENT -------------------------------------------------------

CREATE TABLE department(
	department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	department_name varchar2(32 char),
	CONSTRAINT pk_department PRIMARY KEY(department_id)
);

INSERT INTO DEPARTMENT(department_name)
VALUES ('Data and AI');
INSERT INTO DEPARTMENT(department_name)
VALUES ('Development');
INSERT INTO DEPARTMENT(department_name)
VALUES ('Management');
INSERT INTO DEPARTMENT(department_name)
VALUES ('Product Delivery');
INSERT INTO DEPARTMENT(department_name)
VALUES ('HR');
COMMIT;

--------------------------------------------- EMPLOYEE -------------------------------------------------------

CREATE TABLE EMPLOYEE(
	person_number number(6) GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar2(64 char),
	last_name varchar2(32 char) NOT NULL,
	hire_date DATE DEFAULT SYSDATE NOT NULL,
	birth_date DATE,
	department_id NUMBER NOT NULL,
	salary number(8, 2) CHECK (salary >= 0),
	manager_id number(6),
	commission_pct number,
	CONSTRAINT pk_employee PRIMARY KEY(person_number),
	CONSTRAINT fk_employee_department FOREIGN KEY(department_id) REFERENCES department(department_id),
	CONSTRAINT fk_employee_manager FOREIGN KEY(manager_id) REFERENCES employee(person_number)
);

DECLARE
	v_emp_count NUMBER := 0;
BEGIN
	SELECT count(*)
	INTO v_emp_count
	FROM employee;
	
	IF v_emp_count = 0 THEN
		FOR i IN 1..2000 LOOP
			INSERT INTO employee(first_name, last_name, birth_date, department_id, salary, manager_id)
			VALUES(
				dbms_random.string('A', 20),
				dbms_random.string('A', 10),
				(SELECT DATE '1980-01-01' + trunc(dbms_random.value(-365, 365))),
				(SELECT department_id FROM department ORDER BY dbms_random.value FETCH FIRST 1 ROW ONLY),
				dbms_random.value(0, 5000),
				(SELECT max(person_number) FROM (SELECT person_number FROM employee ORDER BY dbms_random.value FETCH FIRST 1 ROW ONLY))
			);
		END LOOP;
		COMMIT;
	END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_check_birthdate
BEFORE INSERT OR UPDATE ON employee
FOR EACH ROW
BEGIN
	IF :NEW.birth_date > add_months(:NEW.hire_date, -216) THEN -- 216 = 12 * 18
		RAISE_APPLICATION_ERROR(-20001, 'The employee must be at least 18 years old on the hire date.');
	END IF;
END;
/

INSERT INTO employee(first_name, last_name, birth_date, department_id, salary, manager_id)
VALUES('Alexandru Petrut', 'Ursu', to_date('16-01-2004', 'DD-MM-YYYY'), 1, 1234, 5);
COMMIT;

ALTER TABLE employee
ADD employee_metadata clob CHECK (employee_metadata IS json);

UPDATE EMPLOYEE e
SET employee_metadata = '{
	"phone": "+4077123456",
	"linkedin": "linkedin.com/in/placeholder",
	"languages": ["Romanian", "English"],
	"emergencyContact": {
		"name": "placeholder",
		"phone": "+4077456123"
	}
}'
WHERE e.LAST_NAME = 'Ursu';

UPDATE employee SET commission_pct = dbms_random.value(0, 1);
UPDATE employee SET commission_pct = round(commission_pct, 1);

--------------------------------------------- PROJECT -------------------------------------------------------

CREATE TABLE project(
	project_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	project_code varchar2(12 char) NOT NULL,
	project_name varchar2(32 char) NOT NULL,
	department_id NUMBER NOT NULL,
	CONSTRAINT pk_project PRIMARY KEY(project_id),
	CONSTRAINT fk_project_department FOREIGN KEY(department_id) REFERENCES department(department_id)
);

DECLARE
	v_project_count NUMBER := 0;
BEGIN
	SELECT count(*)
	INTO v_project_count
	FROM project;

	IF v_project_count = 0 THEN 
		FOR i IN 1..500 LOOP
			INSERT INTO project(project_code, project_name, department_id)
			VALUES(
				dbms_random.string('A', 10),
				dbms_random.string('A', 20),
				(SELECT department_id FROM department ORDER BY dbms_random.value FETCH FIRST 1 ROW ONLY)
			);
		END LOOP;
		COMMIT;
	END IF;
END;
/

INSERT INTO project(project_code, project_name, department_id)
VALUES('INTGR999BHD', 'Grant BHD', 1);
COMMIT;

CREATE TABLE task(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	task_details varchar2(16 char),
	project_id NUMBER NOT NULL,
	CONSTRAINT pk_task PRIMARY KEY(id),
	CONSTRAINT fk_task_project FOREIGN KEY(project_id) REFERENCES project(project_id)
);

INSERT INTO task(task_details, project_id)
VALUES('05 - Trainees', (SELECT project_id FROM project WHERE project_code = 'INTGR999BHD'));
COMMIT;

--------------------------------------------- TIMECARD -------------------------------------------------------

CREATE TABLE TIMECARD(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	status varchar2(16 char) CHECK (status IN ('SAVED', 'SUBMITTED', 'APPROVED', 'REJECTED')),
	start_date DATE NOT NULL,
	submission_date DATE,
	employee_id NUMBER(6) NOT NULL,
	CONSTRAINT pk_timecard PRIMARY KEY (id),
	CONSTRAINT fk_timecard_employee FOREIGN KEY(employee_id) REFERENCES employee(person_number)
);

INSERT INTO timecard(status, start_date, submission_date, employee_id)
values('SAVED', to_date('07-05-2026', 'MM-DD-YY'), NULL, (SELECT person_number FROM employee WHERE last_name = 'Ursu'));
INSERT INTO timecard(status, start_date, submission_date, employee_id)
values('SAVED', to_date('06-29-2026', 'MM-DD-YY'), NULL, (SELECT person_number FROM employee WHERE last_name = 'Ursu'));
INSERT INTO timecard(status, start_date, submission_date, employee_id)
values('SAVED', to_date('06-22-2026', 'MM-DD-YY'), NULL, (SELECT person_number FROM employee WHERE last_name = 'Ursu'));
COMMIT;

--------------------------------------------- TIMECARD ENTRY -------------------------------------------------------

CREATE TABLE TIMECARD_ENTRY(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	timecard_id NUMBER NOT NULL,
	project_id NUMBER NOT NULL,
	time_type varchar2(16 char) CHECK (time_type IN ('OVERTIME', 'REGULAR')),
	location varchar2(32 char) CHECK (location IN ('OFFICE', 'HOME', 'RELOCATED')),
	absences number,
	task_id number,
	relocated_country varchar2(32 char),
	CONSTRAINT pk_timecard_entry PRIMARY KEY(id),
	CONSTRAINT fk_timecard_entry_timecard FOREIGN KEY(timecard_id) REFERENCES timecard(id),
	CONSTRAINT fk_timecard_entry_project FOREIGN KEY(project_id) REFERENCES project(project_id),
	CONSTRAINT fk_timecard_entry_task FOREIGN KEY(task_id) REFERENCES task(id)
);

/*
	--------------	   ------------
	| DEPARTMENT |  -> | EMPLOYEE |
	--------------     ------------
	      |					  |
	      v					  v
	-----------			------------
	| PROJECT |			| TIMECARD |
	-----------			------------
	      |					  |
	      |					  |	
	      -------      --------
	      	    |      |
	      	    v      v
  	       ------------------	  --------------
  	       | TIMECARD_ENTRY | ->  | WORK_ENTRY |
  	       ------------------	  --------------
        As there is a cycle TIMECARD_ENTRY - TIMECARD - EMPLOYEE - DEPARTMENT - PROJECT
        we have to prevent the following unexpected behaviour:
      ** An user inserts a project_code into one of his timecard entries, but that project code does not
      * exist in the user's department
      * so we get the department id of the project in the new timecard entry
      * and the department id of the user
      * and make sure they are the same before inserting or updating
*/
CREATE OR REPLACE TRIGGER trg_check_project_department
BEFORE INSERT OR UPDATE ON timecard_entry
FOR EACH ROW
DECLARE
v_project_department_id NUMBER;
v_employee_department_id NUMBER;
BEGIN
	-- project department
	SELECT p.department_id 
	INTO v_project_department_id
	FROM project p
	WHERE p.project_id = :NEW.project_id;

	-- employee department
	SELECT e.department_id
	INTO v_employee_department_id
	FROM timecard t
	JOIN employee e ON t.employee_id = e.person_number
	WHERE t.id = :NEW.timecard_id;

	IF (v_project_department_id <> v_employee_department_id) THEN
		RAISE_APPLICATION_ERROR(-20002, 'Cannot insert a timecard entry with a project that is not from your department.');
	END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_check_project_task
BEFORE INSERT OR UPDATE ON timecard_entry
FOR EACH ROW
DECLARE
	v_count NUMBER;
BEGIN
	SELECT count(*)
	INTO v_count
	FROM task
	WHERE id = :NEW.task_id
	AND project_id = :NEW.project_id;

	IF v_count = 0 THEN
		RAISE_APPLICATION_ERROR(-20005, 'This task does not belong to this project');
	END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_check_timecard_submitted
BEFORE INSERT OR UPDATE ON timecard_entry
FOR EACH ROW
DECLARE
	v_timecard_submitted NUMBER;
BEGIN
	SELECT count(*)
	INTO v_timecard_submitted
	FROM timecard
	WHERE id = :NEW.timecard_id
	AND status IN ('SUBMITTED', 'APPROVED');

	IF v_timecard_submitted > 0 THEN
		RAISE_APPLICATION_ERROR(-20006, 'You cannot enter or edit this timecard.');
	END IF;
END;
/

INSERT INTO timecard_entry(timecard_id, project_id, time_type, location, absences, task_id, relocated_country)
values((SELECT max(id) FROM timecard), (SELECT project_id FROM project WHERE project_code = 'INTGR999BHD'), 'REGULAR', 'HOME', NULL, (SELECT max(id) FROM task), null);
INSERT INTO timecard_entry(timecard_id, project_id, time_type, location, absences, task_id, relocated_country)
values((SELECT max(id) FROM timecard), (SELECT project_id FROM project WHERE project_code = 'INTGR999BHD'), 'REGULAR', 'OFFICE', NULL, (SELECT max(id) FROM task), null);
COMMIT;

--------------------------------------------- WORK ENTRY -------------------------------------------------------

CREATE TABLE work_entry(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	work_date DATE NOT NULL,
	start_time DATE,
	stop_time DATE,
	worked_hours number(2) NOT NULL,
	timecard_entry_id NUMBER NOT NULL,
	CONSTRAINT pk_work_entry PRIMARY KEY(id),
	CONSTRAINT fk_work_entry_timecard_entry FOREIGN KEY(timecard_entry_id) REFERENCES timecard_entry(id)
);

CREATE OR REPLACE TRIGGER trg_check_start_stop
BEFORE INSERT OR UPDATE ON work_entry
FOR EACH ROW
BEGIN
	IF :NEW.stop_time < :NEW.start_time THEN
		RAISE_APPLICATION_ERROR(-20003, 'The stop time should not be before start time.');
	END IF;
END;
/

CREATE OR REPLACE FUNCTION td(p_date varchar2) 
RETURN DATE
IS
BEGIN
	RETURN to_date(p_date, 'DD-MM-YYYY');
END;
/

CREATE OR REPLACE FUNCTION tdt(p_datetime varchar2)
RETURN DATE
IS
BEGIN
	RETURN to_date(p_datetime, 'DD-MM-YYYY HH24:MI:SS');
END;
/

CREATE OR REPLACE PROCEDURE insert_work_entry(
	p_working_date IN varchar2,
	p_start_time IN varchar2,
	p_stop_time IN varchar2,
	p_worked_hours IN NUMBER,
	p_timecard_entry_id IN NUMBER
)
IS
BEGIN
	INSERT INTO work_entry(work_date, start_time, stop_time, worked_hours, timecard_entry_id)
	VALUES(td(p_working_date), tdt(p_working_date|| ' ' || p_start_time), tdt(p_working_date|| ' ' || p_stop_time), p_worked_hours, p_timecard_entry_id);
	COMMIT;
END;
/

SELECT * FROM timecard_entry

BEGIN
	insert_work_entry('06-07-2026', '09:00:00', '17:00:00', 8, 16);
	insert_work_entry('07-07-2026', '09:00:00', '17:00:00', 8, 16);
	insert_work_entry('08-07-2026', '09:00:00', '17:00:00', 8, 16);
	insert_work_entry('09-07-2026', '09:00:00', '17:00:00', 8, 17);
	insert_work_entry('10-07-2026', '09:00:00', '17:00:00', 8, 17);
END;
