DROP TABLE debug_log;

CREATE TABLE debug_log(
	log_id		NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	log_time	timestamp DEFAULT systimestamp,
	module_name	varchar2(100),
	line_no		NUMBER,
	log_message	varchar2(4000),
	session_id	varchar2(50) DEFAULT sys_context('USERENV', 'SESSIONID'),
	log_level	number(1) NOT NULL
);