CREATE TABLE bs_book(
	book_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	isbn varchar2(17) NOT NULL,
	title varchar2(32 char),
	price number(8, 2),
	author_id NUMBER NOT NULL,
	publisher_id NUMBER NOT NULL,
	CONSTRAINT fk_author_id_book FOREIGN KEY (author_id) REFERENCES bs_author(author_id),
	CONSTRAINT fk_publisher_id_book FOREIGN KEY (publisher_id) REFERENCES bs_publisher(publisher_id)
);