CREATE TABLE bs_customer(
	customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	cnp varchar2(13 char),
	first_name varchar2(64 char),
	last_name varchar2(64 char),
	email varchar2(64 char),
	country_id NUMBER NOT NULL,
	CONSTRAINT fk_country_id_customer FOREIGN KEY (country_id) REFERENCES bs_country(country_id)
);