CREATE TABLE bs_order(
	order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	customer_id NUMBER NOT NULL,
	order_date DATE DEFAULT sysdate NOT NULL,
	CONSTRAINT fk_customer_id_order FOREIGN KEY (customer_id) REFERENCES bs_customer(customer_id)
);