CREATE TABLE bs_order_item(
	order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	order_id NUMBER NOT NULL,
	book_id NUMBER NOT NULL,
	quantity NUMBER NOT NULL CHECK (quantity > 0),
	unit_price number(8, 2),
	CONSTRAINT fk_order_id_order_item FOREIGN KEY (order_id) REFERENCES bs_order(order_id),
	CONSTRAINT fk_book_id_order_item FOREIGN KEY (book_id) REFERENCES bs_book(book_id)
);