CREATE TABLE bs_review(
	review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	stars number(1) NOT NULL CHECK (stars BETWEEN 1 AND 5),
	message varchar2(4000 char),
	customer_id NUMBER NOT NULL,
	book_id NUMBER NOT NULL,
	CONSTRAINT fk_customer_id_review FOREIGN KEY (customer_id) REFERENCES bs_customer(customer_id),
	CONSTRAINT fk_book_id_review FOREIGN KEY (book_id) REFERENCES bs_book(book_id)
);