CREATE TABLE Fact_Book_Sales(
	sales_fact_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	date_key number(8) NOT NULL,
	customer_key NUMBER NOT NULL,
	book_key NUMBER NOT NULL,
	order_id NUMBER NOT NULL,
	quantity NUMBER NOT NULL,
	unit_price number(8, 2) NOT NULL,
	sales_amount number(10, 2) NOT NULL,
	CONSTRAINT pk_fact_book_sales PRIMARY KEY (sales_fact_id),
	CONSTRAINT fk_fact_sales_date FOREIGN KEY (date_key) REFERENCES dim_date(date_key),
	CONSTRAINT fk_fact_sales_customer FOREIGN KEY (customer_key) REFERENCES dim_customer(customer_key),
	CONSTRAINT fk_fact_sales_book FOREIGN KEY (book_key) REFERENCES dim_book(book_key),
	CONSTRAINT ck_fact_sales_quantity CHECK (quantity > 0),
	CONSTRAINT ck_fact_sales_amount CHECK (sales_amount >= 0)
);

INSERT INTO fact_book_sales(
	date_key,
	customer_key,
	book_key,
	order_id,
	quantity,
	unit_price,
	sales_amount
)
SELECT d.date_key, o.customer_id, oi.book_id, o.order_id, oi.quantity, oi.unit_price, oi.quantity * oi.unit_price
FROM bs_order o
JOIN bs_order_item oi ON oi.order_id = o.order_id
JOIN dim_date d ON d.full_date = trunc(o.order_date);
