CREATE TABLE project(
	project_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	project_code varchar2(12 char) NOT NULL,
	project_name varchar2(32 char) NOT NULL,
	department_id NUMBER NOT NULL,
	CONSTRAINT pk_project PRIMARY KEY(project_id),
	CONSTRAINT fk_project_department FOREIGN KEY(department_id) REFERENCES department(department_id)
);

DECLARE
	v_project_count NUMBER := 0;
BEGIN
	SELECT count(*)
	INTO v_project_count
	FROM project;

	IF v_project_count = 0 THEN 
		FOR i IN 1..500 LOOP
			INSERT INTO project(project_code, project_name, department_id)
			VALUES(
				dbms_random.string('A', 10),
				dbms_random.string('A', 20),
				(SELECT department_id FROM department ORDER BY dbms_random.value FETCH FIRST 1 ROW ONLY)
			);
		END LOOP;
		COMMIT;
	END IF;
END;
/

INSERT INTO project(project_code, project_name, department_id)
VALUES('INTGR999BHD', 'Grant BHD', 1);
COMMIT;