CREATE TABLE task(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	task_details varchar2(16 char),
	project_id NUMBER NOT NULL,
	CONSTRAINT pk_task PRIMARY KEY(id),
	CONSTRAINT fk_task_project FOREIGN KEY(project_id) REFERENCES project(project_id)
);

INSERT INTO task(task_details, project_id)
VALUES('05 - Trainees', (SELECT project_id FROM project WHERE project_code = 'INTGR999BHD'));
COMMIT;