CREATE TABLE TIMECARD_ENTRY(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	timecard_id NUMBER NOT NULL,
	project_id NUMBER NOT NULL,
	time_type varchar2(16 char) CHECK (time_type IN ('OVERTIME', 'REGULAR')),
	location varchar2(32 char) CHECK (location IN ('OFFICE', 'HOME', 'RELOCATED')),
	absences varchar2(32 char),
	task_id number,
	relocated_country varchar2(32 char),
	CONSTRAINT pk_timecard_entry PRIMARY KEY(id),
	CONSTRAINT fk_timecard_entry_timecard FOREIGN KEY(timecard_id) REFERENCES timecard(id),
	CONSTRAINT fk_timecard_entry_project FOREIGN KEY(project_id) REFERENCES project(project_id),
	CONSTRAINT fk_timecard_entry_task FOREIGN KEY(task_id) REFERENCES task(id)
);

/*
	--------------	   ------------
	| DEPARTMENT |  -> | EMPLOYEE |
	--------------     ------------
	      |					  |
	      v					  v
	-----------			------------
	| PROJECT |			| TIMECARD |
	-----------			------------
	      |					  |
	      |					  |	
	      -------      --------
	      	    |      |
	      	    v      v
  	       ------------------	  --------------
  	       | TIMECARD_ENTRY | ->  | WORK_ENTRY |
  	       ------------------	  --------------
        As there is a cycle TIMECARD_ENTRY - TIMECARD - EMPLOYEE - DEPARTMENT - PROJECT
        we have to prevent the following unexpected behaviour:
      ** An user inserts a project_code into one of his timecard entries, but that project code does not
      * exist in the user's department
      * so we get the department id of the project in the new timecard entry
      * and the department id of the user
      * and make sure they are the same before inserting or updating
*/
CREATE OR REPLACE TRIGGER trg_check_project_department
BEFORE INSERT OR UPDATE ON timecard_entry
FOR EACH ROW
DECLARE
v_project_department_id NUMBER;
v_employee_department_id NUMBER;
BEGIN
	-- project department
	SELECT p.department_id 
	INTO v_project_department_id
	FROM project p
	WHERE p.project_id = :NEW.project_id;

	-- employee department
	SELECT e.department_id
	INTO v_employee_department_id
	FROM timecard t
	JOIN employee e ON t.employee_id = e.person_number
	WHERE t.id = :NEW.timecard_id;

	IF (v_project_department_id <> v_employee_department_id) THEN
		RAISE_APPLICATION_ERROR(-20002, 'Cannot insert a timecard entry with a project that is not from your department.');
	END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_check_project_task
BEFORE INSERT OR UPDATE ON timecard_entry
FOR EACH ROW
DECLARE
	v_count NUMBER;
BEGIN
	SELECT count(*)
	INTO v_count
	FROM task
	WHERE id = :NEW.task_id
	AND project_id = :NEW.project_id;

	IF v_count = 0 THEN
		RAISE_APPLICATION_ERROR(-20005, 'This task does not belong to this project');
	END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_check_timecard_submitted
BEFORE INSERT OR UPDATE ON timecard_entry
FOR EACH ROW
DECLARE
	v_timecard_submitted NUMBER;
BEGIN
	SELECT 1
	INTO v_timecard_submitted
	FROM timecard
	WHERE id = :NEW.timecard_id
	AND status = IN ('SUBMITTED', 'APPROVED');

	IF v_timecard_submitted = 1 THEN
		RAISE_APPLICATION_ERROR(-20006, 'You cannot enter or edit this timecard.');
	END IF;
END;
/

INSERT INTO timecard_entry(timecard_id, project_id, time_type, location, absences, task_id, relocated_country)
values(1, (SELECT project_id FROM project WHERE project_code = 'INTGR999BHD'), 'REGULAR', 'HOME', NULL, 1, null);
INSERT INTO timecard_entry(timecard_id, project_id, time_type, location, absences, task_id, relocated_country)
values(1, (SELECT project_id FROM project WHERE project_code = 'INTGR999BHD'), 'REGULAR', 'OFFICE', NULL, 1, null);
COMMIT;