CREATE TABLE work_entry(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	work_date DATE NOT NULL,
	start_time DATE,
	stop_time DATE,
	worked_hours number(2) NOT NULL,
	timecard_entry_id NUMBER NOT NULL,
	CONSTRAINT pk_work_entry PRIMARY KEY(id),
	CONSTRAINT fk_work_entry_timecard_entry FOREIGN KEY(timecard_entry_id) REFERENCES timecard_entry(id)
);

CREATE OR REPLACE TRIGGER trg_check_start_stop
BEFORE INSERT OR UPDATE ON work_entry
FOR EACH ROW
BEGIN
	IF :NEW.stop_time < :NEW.start_time THEN
		RAISE_APPLICATION_ERROR(-20003, 'The stop time should not be before start time.');
	END IF;
END;
/

CREATE OR REPLACE FUNCTION td(p_date varchar2) 
RETURN DATE
IS
BEGIN
	RETURN to_date(p_date, 'DD-MM-YYYY');
END;
/

CREATE OR REPLACE FUNCTION tdt(p_datetime varchar2)
RETURN DATE
IS
BEGIN
	RETURN to_date(p_datetime, 'DD-MM-YYYY HH24:MI:SS');
END;
/

CREATE OR REPLACE PROCEDURE insert_work_entry(
	p_working_date IN varchar2,
	p_start_time IN varchar2,
	p_stop_time IN varchar2,
	p_worked_hours IN NUMBER,
	p_timecard_entry_id IN NUMBER
)
IS
BEGIN
	INSERT INTO work_entry(work_date, start_time, stop_time, worked_hours, timecard_entry_id)
	VALUES(td(p_working_date), tdt(p_working_date|| ' ' || p_start_time), tdt(p_working_date|| ' ' || p_stop_time), p_worked_hours, p_timecard_entry_id);
	COMMIT;
END;

BEGIN
	insert_work_entry('06-07-2026', '09:00:00', '17:00:00', 8, 5);
	insert_work_entry('07-07-2026', '09:00:00', '17:00:00', 8, 5);
	insert_work_entry('08-07-2026', '09:00:00', '17:00:00', 8, 5);
	insert_work_entry('09-07-2026', '09:00:00', '17:00:00', 8, 4);
	insert_work_entry('10-07-2026', '09:00:00', '17:00:00', 8, 4);
END;