CREATE TABLE absences(
	absence_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	absence_type varchar2(32 char) CHECK (absence_type IN ('Annual Leave', 'Medical Leave', 'Public Holidays')),
	start_time DATE,
	end_time DATE,
	employee_id NUMBER NOT NULL,
	CONSTRAINT fk_absences_emp FOREIGN KEY (employee_id) REFERENCES employee(emp_id)
);