ATE TABLE absence_stage(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	monday varchar2(32 char),
	tuesday varchar2(32 char),
	wednesday varchar2(32 char),
	thursday varchar2(32 char),
	friday varchar2(32 char),
	employee_id NUMBER NOT NULL,
	CONSTRAINT fk_absence_stage_emp FOREIGN KEY (employee_id) REFERENCES employee(emp_id)
);