CREATE TABLE attendance_report(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	participant_name varchar2(128 char),
	first_join DATE,
	last_leave DATE,
	email varchar2(128 char),
	participantID varchar2(128 char),
	ROLE varchar2(16 char),
	session_name varchar2(64 char)
);