CREATE TABLE department(
	department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	location_name varchar2(64 char),
	location_code varchar2(4 char),
	name varchar2(64 char),
	discipline_name varchar2(64 char)
);