CREATE TABLE employee(
	emp_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name varchar2(64 char),
	last_name varchar2(64 char),
	birth_date DATE,
	hire_date DATE,
	email varchar2(128 char),
	grade varchar2(64 char),
	department_id NUMBER NOT NULL,
	CONSTRAINT fk_emp_dep FOREIGN KEY (department_id) REFERENCES department(department_id)
);