CREATE TABLE exam_absence_schedule(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	employee_id NUMBER NOT NULL,
	absence_day DATE,
	absence_type varchar2(2 char),
	absence_hours number(1),
	CONSTRAINT fk_exam_absence_emp FOREIGN KEY (employee_id) REFERENCES employee(emp_id)
);

INSERT INTO exam_absence_schedule(
	employee_id,
	absence_day,
	absence_type,
	absence_hours
)
SELECT employee_id,
to_date(regexp_substr(day_value, '[^/]+', 1, 1),
		'DD-MM-YYYY') AS absence_day,
regexp_substr(day_value, '[^/]+', 1, 2) AS absence_type,
to_number(regexp_substr(day_value, '[^/]+', 1, 3)) AS absence_hours
FROM absence_stage
unpivot(
	day_value FOR day_name IN (
		monday,
		tuesday,
		wednesday,
		thursday,
		friday
	)
);