CREATE TABLE timesheet(
	entry_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	entry_day DATE,
	number_of_reported_hours number(1),
	work_type varchar2(8 char),
	start_time DATE,
	end_time DATE,
	employee_id NUMBER NOT NULL,
	CONSTRAINT fk_timesheet_emp FOREIGN KEY (employee_id) REFERENCES employee(emp_id)
);